Removing throttling policy as a workaround to an issue with SNS
cfn-modules/alerting pull request #10
Opened 2020-10-02 07:04 UTC by andreaswittig

See https://cloudonaut.io/loosing-trust-in-aws-sns-broken-for-24-days/ for details

2020-10-02 07:04 UTC, andreaswittig commented
test

2020-10-02 08:49 UTC, michaelwittig requested changes
You also need to bump the version in `package.json`

2020-10-03 14:49 UTC, michaelwittig commented
test

2020-10-03 14:49 UTC, michaelwittig approved these changes

2020-10-03 14:54 UTC, merged

2020-10-07 07:09 UTC, andreaswittig reviewed
👍